name: On Challenge Submitted

on:
  issues:
    types:
    - opened

jobs:
  labelling:
    name: 'Add a label on submission: review-required'

    runs-on: ubuntu-latest

    steps:
    - name: Get event payload
      shell: pwsh
      run: |
        $payload = "${{ toJSON(github) }}"
        echo $payload
